version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    env_file: .env
    ports:
      - "25:25"       # SMTP
      - "143:143"     # IMAP
      - "587:587"     # Submission (TLS)
      - "993:993"     # Secure IMAP
      - "110:110"     # POP3
    volumes:
      - ./mail-data/:/var/mail/
      - ./mail-state/:/var/mail-state/
      - ./mail-logs/:/var/log/mail/
      - ./config/:/tmp/docker-mailserver/
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - no-new-privileges:true

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    ports:
      - "8888:80"
    restart: unless-stopped
    volumes:
      - rainloop-data:/rainloop/data

volumes:
  rainloop-data:
